### ISSUE TITLE
posix_spawn error 8

### ISSUE THREAD

**Issue by JohnHWC** [erluko/WakeWatcher#3]
WakeWatcher had a spawn error on mac osx 10.9.5:
Starting Wake Watcher!
WakeWatcher[3311:507] Watcher <WakeWatcher: 0x7fe3fb602200>
WakeWatcher[3311:507] receiveWakeNote: NSWorkspaceDidWakeNotification
WakeWatcher[3311:507] Attempting to execute: '/Users/john/.onwake'
WakeWatcher[3311:507] Error executing: '/Users/john/.onwake': Couldn't posix_spawn: error 8
...
I was unable to determine precisely what caused the spawn error.
Any suggestions?
Thanks

**Comment by erluko** [comment]
This means that `launchedTaskWithLaunchPath:arguments:` failed.

According to `errno.h` error 8 is ENOEXEC. According to the man page for `posix_spawn` it issues ENOEXEC when:

> The new process file has the appropriate access per-mission, permission,
> mission, but has an unrecognized format (e.g., an invalid magic number in its header)

Try to run `~/.onwake` by hand in the terminal. The error there will hopefully be more informative.
